// automatically generated by the FlatBuffers compiler, do not modify

export enum AuthenticatorAttachment {
  /**
   * Request a device that is part of the machine aka inseperable.
   * <https://www.w3.org/TR/webauthn/#attachment>
   */
  Platform = 0,

  /**
   * Request a device that can be seperated from the machine aka an external token.
   * <https://www.w3.org/TR/webauthn/#attachment>
   */
  CrossPlatform = 1
}
