// automatically generated by the FlatBuffers compiler, do not modify

export enum AttestationConveyancePreference {
  /**
   * Do not request attestation.
   * <https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-none>
   */
  None = 0,

  /**
   * Request attestation in a semi-anonymized form.
   * <https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-indirect>
   */
  Indirect = 1,

  /**
   * Request attestation in a direct form.
   * <https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-direct>
   */
  Direct = 2
}
