// automatically generated by the FlatBuffers compiler, do not modify

export enum AuthenticatorTransport {
  /**
   * <https://www.w3.org/TR/webauthn/#dom-authenticatortransport-usb>
   */
  Usb = 0,

  /**
   * <https://www.w3.org/TR/webauthn/#dom-authenticatortransport-nfc>
   */
  Nfc = 1,

  /**
   * <https://www.w3.org/TR/webauthn/#dom-authenticatortransport-ble>
   */
  Ble = 2,

  /**
   * <https://www.w3.org/TR/webauthn/#dom-authenticatortransport-internal>
   */
  Internal = 3,

  /**
   * Hybrid transport, formerly caBLE. Part of the level 3 draft specification.
   * <https://w3c.github.io/webauthn/#dom-authenticatortransport-hybrid>
   */
  Hybrid = 4,

  /**
   * Test transport; used for Windows 10.
   */
  Test = 5
}
