// automatically generated by the FlatBuffers compiler, do not modify

export enum UserVerificationPolicy {
  /**
   * <https://www.w3.org/TR/webauthn/#dom-userverificationrequirement-preferred>
   */
  Preferred = 0,

  /**
   * <https://www.w3.org/TR/webauthn/#dom-userverificationrequirement-required>
   */
  Required = 1,

  /**
   * <https://www.w3.org/TR/webauthn/#dom-userverificationrequirement-discouraged>
   */
  Discouraged = 2
}
