// automatically generated by the FlatBuffers compiler, do not modify

export { NumberRegistration, NumberRegistrationT } from './auth/kv/number-registration.js';
export { VerifiedNumber, VerifiedNumberT } from './auth/kv/verified-number.js';
