// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { CredentialCreationOptions, CredentialCreationOptionsT } from '../auth/web-authn/credential-creation-options.js';


export class VerifyNumberRes implements flatbuffers.IUnpackableObject<VerifyNumberResT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VerifyNumberRes {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVerifyNumberRes(bb:flatbuffers.ByteBuffer, obj?:VerifyNumberRes):VerifyNumberRes {
  return (obj || new VerifyNumberRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVerifyNumberRes(bb:flatbuffers.ByteBuffer, obj?:VerifyNumberRes):VerifyNumberRes {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VerifyNumberRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

options(obj?:CredentialCreationOptions):CredentialCreationOptions|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CredentialCreationOptions()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startVerifyNumberRes(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, optionsOffset, 0);
}

static endVerifyNumberRes(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVerifyNumberRes(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  VerifyNumberRes.startVerifyNumberRes(builder);
  VerifyNumberRes.addOptions(builder, optionsOffset);
  return VerifyNumberRes.endVerifyNumberRes(builder);
}

unpack(): VerifyNumberResT {
  return new VerifyNumberResT(
    (this.options() !== null ? this.options()!.unpack() : null)
  );
}


unpackTo(_o: VerifyNumberResT): void {
  _o.options = (this.options() !== null ? this.options()!.unpack() : null);
}
}

export class VerifyNumberResT implements flatbuffers.IGeneratedObject {
constructor(
  public options: CredentialCreationOptionsT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const options = (this.options !== null ? this.options!.pack(builder) : 0);

  return VerifyNumberRes.createVerifyNumberRes(builder,
    options
  );
}
}
