// automatically generated by the FlatBuffers compiler, do not modify

package Auth.API

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
@kotlin.ExperimentalUnsignedTypes
class ErrorRes : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ErrorRes {
        __init(_i, _bb)
        return this
    }
    val error : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val errorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun errorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_1_4()
        fun getRootAsErrorRes(_bb: ByteBuffer): ErrorRes = getRootAsErrorRes(_bb, ErrorRes())
        fun getRootAsErrorRes(_bb: ByteBuffer, obj: ErrorRes): ErrorRes {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createErrorRes(builder: FlatBufferBuilder, errorOffset: Int) : Int {
            builder.startTable(1)
            addError(builder, errorOffset)
            return endErrorRes(builder)
        }
        fun startErrorRes(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addError(builder: FlatBufferBuilder, error: Int) = builder.addOffset(0, error, 0)
        fun endErrorRes(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
