// automatically generated by the FlatBuffers compiler, do not modify

package Auth.WebAuthn

@Suppress("unused")
@kotlin.ExperimentalUnsignedTypes
class UserVerificationPolicy private constructor() {
    companion object {
        /**
         * <https://www.w3.org/TR/webauthn/#dom-userverificationrequirement-preferred>
         */
        const val Preferred: Byte = 0
        /**
         * <https://www.w3.org/TR/webauthn/#dom-userverificationrequirement-required>
         */
        const val Required: Byte = 1
        /**
         * <https://www.w3.org/TR/webauthn/#dom-userverificationrequirement-discouraged>
         */
        const val Discouraged: Byte = 2
    }
}
