// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ErrorRes implements flatbuffers.IUnpackableObject<ErrorResT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ErrorRes {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsErrorRes(bb:flatbuffers.ByteBuffer, obj?:ErrorRes):ErrorRes {
  return (obj || new ErrorRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsErrorRes(bb:flatbuffers.ByteBuffer, obj?:ErrorRes):ErrorRes {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ErrorRes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startErrorRes(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, errorOffset, 0);
}

static endErrorRes(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createErrorRes(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  ErrorRes.startErrorRes(builder);
  ErrorRes.addError(builder, errorOffset);
  return ErrorRes.endErrorRes(builder);
}

unpack(): ErrorResT {
  return new ErrorResT(
    this.error()
  );
}


unpackTo(_o: ErrorResT): void {
  _o.error = this.error();
}
}

export class ErrorResT implements flatbuffers.IGeneratedObject {
constructor(
  public error: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const error = (this.error !== null ? builder.createString(this.error!) : 0);

  return ErrorRes.createErrorRes(builder,
    error
  );
}
}
