// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class RelyingParty implements flatbuffers.IUnpackableObject<RelyingPartyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RelyingParty {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRelyingParty(bb:flatbuffers.ByteBuffer, obj?:RelyingParty):RelyingParty {
  return (obj || new RelyingParty()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRelyingParty(bb:flatbuffers.ByteBuffer, obj?:RelyingParty):RelyingParty {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RelyingParty()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRelyingParty(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static endRelyingParty(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRelyingParty(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  RelyingParty.startRelyingParty(builder);
  RelyingParty.addId(builder, idOffset);
  RelyingParty.addName(builder, nameOffset);
  return RelyingParty.endRelyingParty(builder);
}

unpack(): RelyingPartyT {
  return new RelyingPartyT(
    this.id(),
    this.name()
  );
}


unpackTo(_o: RelyingPartyT): void {
  _o.id = this.id();
  _o.name = this.name();
}
}

export class RelyingPartyT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);

  return RelyingParty.createRelyingParty(builder,
    id,
    name
  );
}
}
