name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo bins
      id: cache-cargo
      uses: actions/cache@v3
      env:
        cache-name: cache-planus
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use nightly
      run: rustup default nightly
    - name: Install planus
      run: cargo install --git https://github.com/planus-org/planus planus-cli
    - name: Run checks
      run: planus check **/*.fbs
      shell: zsh {0}
    - name: Build files
      run: planus rust -o rs/src/gen.rs **/*.fbs
      shell: zsh {0}
