name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo bins
      id: cache-cargo
      uses: actions/cache@v3
      env:
        cache-name: cache-planus
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Glob match schemas
      uses: tj-actions/glob@v16
      id: glob
      with:
        files: |
          **/*.fbs
    - name: Use nightly
      run: rustup default nightly
    - name: Install rustfmt
      run: rustup component add rustfmt --toolchain nightly
    - name: Install planus
      run: cargo install --git https://github.com/planus-org/planus planus-cli
    - name: Run checks
      run: planus check ${{ steps.glob.outputs.paths }}
    - name: Build files
      run: planus rust -o bindings/rs/src/gen.rs ${{ steps.glob.outputs.paths }}
