name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Enable globstar
      run: shopt -s globstar
    - name: Use nightly
      run: rustup default nightly
    - name: Install planus
      run: cargo install --git https://github.com/planus-org/planus planus-cli
    - name: Run checks
      run: planus check **/*.fbs
    - name: Build files
      run: planus rust -o rs/src/gen.rs **/*.fbs
